"use strict";

const STORAGE_KEY = "nms-hightech-helper-v2";
const LANGUAGE_KEY = "nms-hightech-helper-language";
const THEME_KEY = "nms-hightech-helper-theme";
let language = localStorage.getItem(LANGUAGE_KEY) === "pt-BR" ? "pt-BR" : "en";
let theme = localStorage.getItem(THEME_KEY) === "purple" ? "purple" : "green";
const TEST_INVENTORY = {
  geodesite: 2, fusion_accelerant: 29, mordite: 7868, fungal_mould: 500, cactus_flesh: 791,
  nitrogen: 750, condensed_carbon: 7653, frost_crystal: 400, sulphurine: 1000, radon: 0,
  solanium: 0, star_bulb: 0, dirty_bronze: 5, herox: 10, lemmium: 0, pyrite: 225,
  pure_ferrite: 799, ammonia: 5535, ionized_cobalt: 0, uranium: 0, lubricant: 12,
  glass: 278, faecium: 6865, gamma_root: 1555, paraffinium: 2001, phosphorus: 0, dioxite: 4928
};
const itemById = Object.fromEntries(NMS_ITEMS.map(item => [item.id, item]));
let inventory = loadInventory();
let screenshots = [];
let saveCandidates = [];
let inventorySources = loadInventorySources();
let lastCalculation = null;
let inventoryFilter = "relevant";
let inventorySearch = "";
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];

function t(text) { return language === "pt-BR" ? (NMS_I18N.ui[text] || text) : text; }
function localizedName(id, englishName) { return language === "pt-BR" ? (NMS_I18N.items[englishName] || englishName) : englishName; }
function applyTheme() { const purple = theme === "purple"; document.body.dataset.theme = theme; document.body.classList.toggle("theme-purple", purple); document.documentElement.dataset.theme = theme; const button = $("#themeToggle"); if (button) { button.setAttribute("aria-pressed", String(purple)); button.title = language === "pt-BR" ? (purple ? "Mudar para o tema verde" : "Mudar para o tema roxo") : (purple ? "Switch to dark-green theme" : "Switch to dark-purple theme"); $("#themeToggleLabel").textContent = language === "pt-BR" ? (purple ? "Verde" : "Roxo") : (purple ? "Green" : "Purple"); } }
function applyLanguage() {
  document.documentElement.lang = language === "pt-BR" ? "pt-BR" : "en";
  document.title = language === "pt-BR" ? "NMS HighTech Helper · Português" : "NMS HighTech Helper";
  const languageLabel = $("#languageLabel"); if (languageLabel) languageLabel.textContent = language === "pt-BR" ? "Idioma" : "Language";
  applyTheme();
  const staticText = {
    ".topbar p": "Offline crafting calculator", ".offline": "OFFLINE", ".context-card .eyebrow": "LOCAL UTILITY", ".context-card strong": "Crafting calculator", ".context-card span": "Inventory stays in this browser",
    '[data-view="workspace"]': "Workspace", '[data-view="data"]': "Recipe data", ".mini-status strong": "Browser storage", ".mini-status small": "No uploads or network calls",
    "#workspaceView .view-heading .eyebrow": "CRAFTING WORKSPACE", "#workspaceView h2": "What are you building?", "#workspaceView .view-heading p": "Load a savegame or enter inventory, then calculate.",
    "label[for=saveInput]": "＋ Load savegame", "#loadTest": "Load test inventory", ".step-card:nth-child(1) .eyebrow": "INVENTORY INPUT", ".step-card:nth-child(1) h3": "Inventory screenshots", ".step-card:nth-child(1) p": "Temporarily paused while savegame reading is explored.", "#addScreenshot": "＋ Add screenshot",
    ".step-card:nth-child(2) .eyebrow": "VERIFICATION", ".step-card:nth-child(2) h3": "Detected inventory", ".step-card:nth-child(2) p": "No entries yet", ".step-card:nth-child(3) .eyebrow": "CALCULATION", ".step-card:nth-child(3) h3": "Crafting target", ".step-card:nth-child(3) p": "Choose a product and quantity below.",
    "#savePanel .eyebrow": "SAVEGAME INPUT", "#savePanel h3": "Choose a save candidate", ".verification-panel .notice p": "Screenshot input is temporarily disabled. Inventory can still be entered manually while savegame reading is explored.",
    ".verification-panel .eyebrow": "CHECK BEFORE CALCULATING", ".verification-panel h3": "Detected inventory", "#addManual": "＋ Add item manually", ".target-panel .eyebrow": "CRAFTING TARGET", ".target-panel h3": "Choose what to build", "#calculateButton": "Calculate requirements",
    "#resultsPanel h3": "Your result will appear here", "#resultsPanel p": "The calculator will separate craftable components from raw resources and show every missing amount.", "#dataView .eyebrow": "REFERENCE", "#dataView h2": "Recipe data", "#dataView p": "Local, editable data powers the dependency engine."
  };
  Object.entries(staticText).forEach(([selector, text]) => { const node = $(selector); if (node) node.textContent = t(text); });
  const saveNotice = $("#savePanel .notice p"); if (saveNotice) saveNotice.innerHTML = `${t("Select one or more save*.hg files manually. The reader ignores metadata files and does not access any folder automatically.")}`;
  const product = $("#productSelect"); if (product) [...product.options].forEach(option => { option.textContent = localizedName(option.value, option.value === "fusion_ignitor" ? "Fusion Ignitor" : "Stasis Device"); });
  const selector = $("#languageSelect"); if (selector) selector.value = language;
  const source = $("#sourceSummary"); const hasPlayer = Object.keys(inventorySources.player || {}).length > 0; const hasContainer = Object.keys(inventorySources.container || {}).length > 0;
  if (source && (hasPlayer || hasContainer)) source.innerHTML = hasContainer ? `<strong>${language === "pt-BR" ? "Fontes do inventário" : "Inventory sources"}:</strong> ${language === "pt-BR" ? "inventário do jogador + contêiner fixo" : "player inventory + fixed container"} <b>${escapeHtml(inventorySources.containerName)}</b>. ${language === "pt-BR" ? "Cada linha mostra sua origem." : "Each row below shows its source breakdown."}` : `<strong>${language === "pt-BR" ? "Fonte do inventário" : "Inventory source"}:</strong> ${language === "pt-BR" ? "somente inventário do jogador. Nenhum contêiner correspondente foi encontrado, então nenhum inventário de contêiner foi incluído." : "player inventory only. No matching fixed container was found, so no container inventory was included."}`;
  const filter = $("#inventoryFilter"); if (filter) { filter.options[0].textContent = t("Needed for selected device"); filter.options[1].textContent = t("Friendly names only"); filter.options[2].textContent = t("All detected items"); filter.options[3].textContent = t("Unmapped save codes"); }
  const search = $("#inventorySearch"); if (search) search.placeholder = t("Name or save code");
  renderShots(); renderInventory(); renderRecipeSummary(); renderSaveCandidates();
  const renderedFilter = $("#inventoryFilter"); if (renderedFilter) { renderedFilter.options[0].textContent = t("Needed for selected device"); renderedFilter.options[1].textContent = t("Friendly names only"); renderedFilter.options[2].textContent = t("All detected items"); renderedFilter.options[3].textContent = t("Unmapped save codes"); }
  const renderedSearch = $("#inventorySearch"); if (renderedSearch) renderedSearch.placeholder = t("Name or save code");
  const detected = $("#detectedSummary"); if (detected && language === "pt-BR") detected.textContent = detected.textContent.replace("item(s) detected", "item(ns) detectado(s)").replace("No entries yet", "Nenhum item ainda");
  if (lastCalculation) renderResults(lastCalculation);
}

function loadInventory() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || {}; } catch { return {}; } }
function loadInventorySources() { try { return JSON.parse(localStorage.getItem(`${STORAGE_KEY}-sources`)) || { player: {}, container: {}, containerName: "" }; } catch { return { player: {}, container: {}, containerName: "" }; } }
function saveInventory() { localStorage.setItem(STORAGE_KEY, JSON.stringify(inventory)); localStorage.setItem(`${STORAGE_KEY}-sources`, JSON.stringify(inventorySources)); }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>'"]/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character])); }
function canonicalId(name) { const clean = name.trim().toLowerCase().replace(/\s+/g, " "); const translated = Object.entries(NMS_I18N.items).find(([, value]) => value.toLowerCase() === clean)?.[0]; const itemId = NMS_ITEMS.find(item => item.name.toLowerCase() === clean)?.id; return NMS_ALIASES[clean] || (translated && itemId) || clean.replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, ""); }
function catalogueItem(id) { const raw = String(id || "").replace(/^\^/, ""); const base = raw.split("#", 1)[0]; return NMS_SAVE_CATALOGUE[raw] || NMS_SAVE_CATALOGUE[raw.toUpperCase()] || NMS_SAVE_CATALOGUE[base] || NMS_SAVE_CATALOGUE[base.toUpperCase()] || null; }
function saveItemInfo(id) { const mapped = NMS_SAVE_ITEM_MAP[id]; const catalogue = catalogueItem(id); return mapped || catalogue ? (mapped || { id, ...catalogue }) : { id: id.toLowerCase(), name: id, unknown: true }; }
function mappedInventory(source) { return Object.entries(source).reduce((map, [rawId, quantity]) => { const item = saveItemInfo(rawId); map[item.id] = (map[item.id] || 0) + quantity; return map; }, {}); }
function sourceLabel(id) { const player = inventorySources.player[id] || 0, container = inventorySources.container[id] || 0; if (!player && !container) return language === "pt-BR" ? "entrada manual/local" : "manual/local entry"; const parts = []; if (player) parts.push(`${language === "pt-BR" ? "jogador" : "player"} ${player.toLocaleString()}`); if (container) parts.push(`${inventorySources.containerName || (language === "pt-BR" ? "contêiner fixo" : "fixed container")} ${container.toLocaleString()}`); return parts.join(" + "); }
function itemDisplay(id) { const mapped = NMS_SAVE_ITEM_MAP[id.toUpperCase()]; const english = mapped?.name || itemById[id]?.name || catalogueItem(id)?.name || id; return localizedName(id, english); }
function showView(view) { $$(".nav-item").forEach(button => button.classList.toggle("active", button.dataset.view === view)); $$(".view").forEach(section => section.classList.toggle("active", section.id === `${view}View`)); }
function toast(message) { const node = $("#toast"); node.textContent = message; node.classList.add("show"); clearTimeout(toast.timer); toast.timer = setTimeout(() => node.classList.remove("show"), 2600); }
function renderShots() { $("#screenshotGrid").innerHTML = Array.from({ length: 3 }, (_, index) => screenshots[index] ? `<div class="screenshot-slot"><img src="${screenshots[index].url}" alt="Inventory screenshot ${index + 1}"><div class="slot-caption">Screenshot ${index + 1} - local only</div><button class="remove-shot" data-remove-shot="${index}" title="Remove" disabled>x</button></div>` : `<div class="screenshot-slot empty"><button data-add-slot="${index}" disabled><strong>+ Screenshot ${index + 1}</strong><br><small>Paused</small></button></div>`).join(""); }
function addImages(files) { [...files].slice(0, 3 - screenshots.length).forEach(file => { if (file.type.startsWith("image/")) screenshots.push({ name: file.name, url: URL.createObjectURL(file) }); }); renderShots(); if (files.length) toast("Image loaded locally. Verify inventory rows below."); }
function formatSaveDate(timestamp) { return timestamp ? new Date(timestamp).toLocaleString() : "date unavailable"; }
function renderSaveCandidates() { const node = $("#saveCandidates"); if (!saveCandidates.length) { node.innerHTML = `<div class="empty-state">Choose a savegame to inspect its inventory and named storage containers.</div>`; return; } node.innerHTML = saveCandidates.map((result, index) => { const matches = result.matchingContainers; const status = result.error ? `Read error: ${escapeHtml(result.error)}` : matches.length === 1 ? `Player inventory: found (${result.playerInventorySlots} slots) · Fixed container: found — ${escapeHtml(matches[0].name)}` : matches.length ? `Player inventory: found (${result.playerInventorySlots} slots) · ${matches.length} matching fixed containers — selection blocked` : `Player inventory: found (${result.playerInventorySlots} slots) · Fixed container: not found`; return `<article class="save-candidate"><div><strong>${escapeHtml(result.fileName)}</strong><small>${result.size.toLocaleString()} bytes · ${escapeHtml(formatSaveDate(result.lastModified))} · version ${escapeHtml(result.version)}</small><small>Platform: ${escapeHtml(result.platform)} · ${escapeHtml(status)}</small></div><button class="secondary-button" data-select-save="${index}" ${matches.length <= 1 && !result.error ? "" : "disabled"}>Use this save</button></article>`; }).join(""); }
function useSaveCandidate(index) { const result = saveCandidates[index]; if (!result || result.matchingContainers.length > 1 || result.error) return; const container = result.matchingContainers[0] || null; inventorySources = { player: mappedInventory(result.playerInventory), container: container ? mappedInventory(container.inventory) : {}, containerName: container ? container.name : "" }; inventory = { ...inventorySources.player }; Object.entries(inventorySources.container).forEach(([id, quantity]) => { inventory[id] = (inventory[id] || 0) + quantity; }); saveInventory(); renderInventory(); if (!container) { $("#saveStatus").textContent = `${result.fileName} · player inventory only`; $("#sourceSummary").innerHTML = `<strong>Inventory source:</strong> player inventory only. No matching fixed container was found, so no container inventory was included.`; toast("Save loaded with player inventory only. No fixed container was included."); return; } $("#saveStatus").textContent = `${result.fileName} · ${container.name}`; $("#sourceSummary").innerHTML = `<strong>Inventory sources:</strong> player inventory + fixed container <b>${escapeHtml(container.name)}</b>. Each row below shows its source breakdown.`; toast(`Save loaded with ${container.name}. Verify the inventory rows.`); }
async function inspectSaveFiles(files) { saveCandidates = []; $("#saveStatus").textContent = "Reading save..."; renderSaveCandidates(); const selected = [...files].filter(file => /^save\d*\.hg$/i.test(file.name)); if (!selected.length) { $("#saveStatus").textContent = "No save*.hg selected"; toast("Choose save.hg, save2.hg, save3.hg, and so on. Metadata files are ignored."); return; } for (const file of selected) { try { saveCandidates.push(await NMS_SAVE_READER.parse(file, await file.arrayBuffer())); } catch (error) { saveCandidates.push({ fileName: file.name, size: file.size, lastModified: file.lastModified, version: "unreadable", platform: "-", playerInventorySlots: 0, matchingContainers: [], error: error.message, playerInventory: {} }); } } $("#saveStatus").textContent = `${saveCandidates.length} save candidate${saveCandidates.length === 1 ? "" : "s"}`; renderSaveCandidates(); }
function recipeDependencyIds(productId) { const ids = new Set(); const visit = id => { if (ids.has(id)) return; ids.add(id); Object.keys(NMS_RECIPES[id]?.ingredients || {}).forEach(visit); }; visit(productId); return ids; }
function ensureInventoryToolbar() { if ($("#inventoryToolbar")) return; $("#inventoryRows").insertAdjacentHTML("beforebegin", `<div class="inventory-toolbar" id="inventoryToolbar"><label>Filter<select id="inventoryFilter"><option value="relevant">Needed for selected device</option><option value="named">Friendly names only</option><option value="all">All detected items</option><option value="unknown">Unmapped save codes</option></select></label><label class="inventory-search">Search<input id="inventorySearch" type="search" placeholder="Name or save code"></label><span id="inventorySummary">No entries yet</span></div>`); $("#inventoryFilter").value = inventoryFilter; $("#inventoryFilter").addEventListener("change", event => { inventoryFilter = event.target.value; renderInventory(); }); $("#inventorySearch").addEventListener("input", event => { inventorySearch = event.target.value.trim().toLowerCase(); renderInventory(); }); }
function renderInventory() { ensureInventoryToolbar(); const allRows = Object.entries(inventory).filter(([, quantity]) => Number(quantity) >= 0).sort(([a], [b]) => itemDisplay(a).localeCompare(itemDisplay(b))); const relevant = recipeDependencyIds($("#productSelect")?.value || "fusion_ignitor"); const rows = allRows.filter(([id]) => { const name = itemDisplay(id), named = Boolean(NMS_SAVE_ITEM_MAP[id.toUpperCase()] || itemById[id] || catalogueItem(id)); const filterMatch = inventoryFilter === "all" || (inventoryFilter === "relevant" && relevant.has(id)) || (inventoryFilter === "named" && named) || (inventoryFilter === "unknown" && !named); return filterMatch && (!inventorySearch || `${name} ${id}`.toLowerCase().includes(inventorySearch)); }); $("#detectedSummary").textContent = allRows.length ? `${allRows.length} item(s) detected` : "No entries yet"; $("#inventorySummary").textContent = `${rows.length} shown of ${allRows.length}`; $("#inventoryRows").innerHTML = rows.length ? rows.map(([id, quantity]) => `<div class="inventory-row" data-row-id="${escapeHtml(id)}"><div><input class="item-name" value="${escapeHtml(itemDisplay(id))}" aria-label="Item name"><span class="row-confidence">${escapeHtml(sourceLabel(id))} · save code: ${escapeHtml(id)}${catalogueItem(id) ? ` · ${escapeHtml(catalogueItem(id).kind)}` : " · unrecognized save object"}</span></div><div class="qty"><input class="item-quantity" type="number" min="0" step="1" value="${Number(quantity)}" aria-label="Quantity"></div><button class="remove-row" data-remove-row="${escapeHtml(id)}" title="Remove item">x</button></div>`).join("") : `<div class="empty-state">No items match this view. Try “All detected items” or clear the search.</div>`; }
function syncInventoryFromDom() { const next = {}; $$(".inventory-row").forEach(row => { const name = row.querySelector(".item-name").value; const quantity = Math.max(0, Math.floor(Number(row.querySelector(".item-quantity").value) || 0)); const id = canonicalId(name); if (id) next[id] = (next[id] || 0) + quantity; }); inventory = next; saveInventory(); renderInventory(); }
function addManualRow() { const id = `new_item_${Date.now()}`; inventory[id] = 0; renderInventory(); const input = $(".inventory-row:last-child .item-name"); if (input) { input.value = ""; input.focus(); } }
function loadTestInventory() { inventory = { ...TEST_INVENTORY }; inventorySources = { player: {}, container: {}, containerName: "" }; saveInventory(); renderInventory(); $("#sourceSummary").textContent = "Inventory source: built-in test fixture. No savegame or fixed container is active."; toast("Test inventory loaded. Recipe requirements were not added to it."); }
function renderResults(result) { const row = item => `<div class="result-row"><div><strong>${escapeHtml(itemDisplay(item.id))}</strong><small>${t("Required")} ${item.required.toLocaleString()} - ${t("Available")} ${item.available.toLocaleString()}</small></div><span class="result-values"><b>${item.covered.toLocaleString()}</b><small>${t("covered")}</small></span><span class="result-values"><b>${item.required.toLocaleString()}</b><small>${t("required")}</small></span><span class="result-missing ${item.missing ? "bad" : ""}">${item.missing ? `-${item.missing.toLocaleString()}` : t("OK")}</span></div>`; const section = (title, rows, empty) => `<div class="result-section"><h4>${t(title)}</h4>${rows.length ? rows.map(row).join("") : `<div class="empty-state">${t(empty)}</div>`}</div>`; $("#resultsPanel").innerHTML = `<div class="result-head"><div><div class="eyebrow">CALCULATION RESULT</div><h3>${escapeHtml(itemDisplay(result.final.id))} x ${result.amount}</h3><p>${result.possible ? t("Every requirement is covered by this inventory.") : t("Gather the missing amounts before crafting.")}</p></div><span class="result-status ${result.possible ? "good" : ""}">${result.possible ? t("READY TO CRAFT") : t("NOT ENOUGH RESOURCES")}</span></div><div class="result-grid">${section("INTERMEDIATE COMPONENTS", result.intermediate, "No intermediate components.")}${section("RAW RESOURCES", result.raw, "No raw resources.")}</div>`; }
function calculate() { syncInventoryFromDom(); const amount = Math.max(1, Math.min(999, Math.floor(Number($("#quantityInput").value) || 1))); $("#quantityInput").value = amount; lastCalculation = NMS_ENGINE.calculate($("#productSelect").value, amount, inventory, NMS_RECIPES, NMS_ITEMS); renderResults(lastCalculation); }
function renderRecipeSummary() { $("#recipeSummary").innerHTML = Object.entries(NMS_RECIPES).map(([id, recipe]) => `<div class="recipe-chip"><strong>${escapeHtml(itemDisplay(id))}</strong><small>${Object.entries(recipe.ingredients).map(([ingredient, quantity]) => `${quantity} x ${escapeHtml(itemDisplay(ingredient))}`).join(" + ")}</small></div>`).join(""); }

document.addEventListener("click", event => { const nav = event.target.closest("[data-view]"); if (nav) showView(nav.dataset.view); const saveButton = event.target.closest("[data-select-save]"); if (saveButton) useSaveCandidate(Number(saveButton.dataset.selectSave)); const slot = event.target.closest("[data-add-slot]"); if (slot && !slot.disabled) $("#screenshotInput").click(); const removeShot = event.target.closest("[data-remove-shot]"); if (removeShot && !removeShot.disabled) { const removed = screenshots.splice(Number(removeShot.dataset.removeShot), 1)[0]; if (removed) URL.revokeObjectURL(removed.url); renderShots(); } const removeRow = event.target.closest("[data-remove-row]"); if (removeRow) { syncInventoryFromDom(); delete inventory[removeRow.dataset.removeRow]; saveInventory(); renderInventory(); } if (event.target.closest("#addManual")) addManualRow(); const testButton = event.target.closest("#loadTest"); if (testButton && !testButton.disabled) loadTestInventory(); if (event.target.closest("#calculateButton")) calculate(); if (event.target.closest("#resetApp")) { inventory = {}; inventorySources = { player: {}, container: {}, containerName: "" }; lastCalculation = null; screenshots.forEach(item => URL.revokeObjectURL(item.url)); screenshots = []; saveInventory(); renderShots(); renderInventory(); $("#sourceSummary").textContent = "No save or fixed container is currently contributing to the inventory."; $("#saveStatus").textContent = "No save selected"; $("#resultsPanel").innerHTML = `<div class="results-placeholder"><span>*</span><h3>Your result will appear here</h3><p>The calculator will separate craftable components from raw resources and show every missing amount.</p></div>`; toast("Local session reset."); } });
$("#addScreenshot").addEventListener("click", () => $("#screenshotInput").click());
$("#screenshotInput").addEventListener("change", event => { addImages(event.target.files); event.target.value = ""; });
$("#saveInput").addEventListener("change", event => { inspectSaveFiles(event.target.files); event.target.value = ""; });
$("#inventoryRows").addEventListener("change", syncInventoryFromDom);
$("#productSelect").addEventListener("change", renderInventory);
$("#languageSelect").addEventListener("change", event => { language = event.target.value === "pt-BR" ? "pt-BR" : "en"; localStorage.setItem(LANGUAGE_KEY, language); applyLanguage(); });
document.addEventListener("click", event => { if (event.target.closest("#themeToggle")) { theme = theme === "purple" ? "green" : "purple"; localStorage.setItem(THEME_KEY, theme); applyTheme(); } });
applyLanguage();
